contentDir = "docs/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = false
enableGitInfo = true
disableKinds = ["RSS"]

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# taxonomyCloud, taxonomyCloudTitle, and taxonomyPageHeader are parallel arrays
taxonomyCloud = []
taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyPageHeader = ["tags", "categories"]
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[imaging]
resampleFilter = "CatmullRom"
quality = 100
anchor = "smart"

[languages]
[languages.en]
title = "Viam Documentation"
description = "Viam Documentation"
languageName ="English"
weight = 1

[sitemap]
  changefreq = 'monthly'
  priority = 0.8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true

[outputs]
section = ["HTML"]

[params]
copyright = "Viam, Inc. - Documentation is licensed under Creative Commons ShareAlike License. "
privacy_policy = "https://www.viam.com/privacy"
includes_dir = "_includes"
archived_version = false
url_latest_version = "https://docs.viam.com/"
algolia_docsearch = true
offlineSearch = false
prism_syntax_highlighting = true
images = ["https://assets-global.website-files.com/62fba5686b6d47fe2a1ed2a6/63404a4db2c39ec3fbf1ed31_viam-open-graph-images.png"]
taxonomiesExcludedFromSitemap = ["tags", "categories"]

version_menu = "SDK Documentation"
[[params.versions]]
 version = "Python SDK Documentation"
 url = "https://python.viam.dev/"
[[params.versions]]
 version = "Go Client SDK Documentation"
 url="https://pkg.go.dev/go.viam.com/rdk"
[[params.versions]]
 version = "TypeScript SDK Documentation"
 url="https://ts.viam.dev/"
[[params.versions]]
 version = "C++ SDK Documentation"
 url="https://cpp.viam.dev/"
# [[params.versions]]
#  version = "Rust SDK Documentation"
#  url = "https://rust.viam.dev/"

[params.ui]
breadcrumb_disable = false
footer_about_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = true  # When true, the section headings work like an accordian.
sidebar_search_disable = true

[params.ui.feedback]
enable = true
yes = 'Glad to hear it! If there is anything we could be doing better, please <a href="https://github.com/viamrobotics/docs/issues/new">create an issue</a>.'
no = "We're sorry about that. If you'd like to talk to us for help, please join the <a href='https://discord.gg/viam'>Community Discord</a>. To ensure we know what's wrong with this page, you can also <a href='https://github.com/viamrobotics/docs/issues/new'>open an issue</a>."

[params.ui.readingtime]
enable = false

[params.links]
[[params.links.user]]
  name ="Twitter"
  url = "https://twitter.com/viamrobotics"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
  name = "Instagram"
  url = "https://www.instagram.com/viamrobotics/"
  icon = "fab fa-instagram"
  desc = "Follow us on Instagram for the latest cool pics of life at Viam!"
[[params.links.user]]
  name = "Linkedin"
  url = "https://www.linkedin.com/company/viaminc/about/"
  icon = "fab fa-linkedin"
  desc = "Connect with Viam on LinkedIn for news and information"
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/viamrobotics/"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Discord"
  url = "https://discord.gg/viam"
  icon = "fab fa-discord"
  desc = "Chat with other project developers"
[[params.links.developer]]
  name = "Developer Help"
  url = "mailto:developers-help@viam.com"
  icon = "fa fa-envelope"
  desc = "Ask questions about the Viam SDK"

[params.github]
repository = "viamrobotics/docs"
branch = "main"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
