site_name: "VIAM Documention, Reference, and Tutorials"
nav:
  - Home: 'index.md'
  - Getting Started:
    - Viam Overview: 'getting-started/high-level-overview.md'
    - Viam's Robot Configuration: 'getting-started/robot-config.md'
  - Product Overviews:
    - app.viam's Organizational Hierarchy: 'product-overviews/organization-management.md'
    - app.viam's Robot Page: 'product-overviews/fleet-management.md'
  - Tutorials: 
    - Tutorials: 'tutorials/tutorials.md'
    - Install VIAM on Raspberry Pi: 'getting-started/installation.md'    
    - ScuttleBot: 'tutorials/scuttlebot.md'
    - Scuttlebot Gamepad: 'tutorials/scuttle-gamepad.md'
    - YahBoom Rover: 'tutorials/yahboom-rover.md'
    - Color Detection using a ScuttleBot: 'tutorials/color-detection-scuttle.md'
    - Control GPIO Pins on a Scuttle Robot: 'tutorials/control-gpio-on-scuttlebot.md'
  - Deep Dives:
    - Viam's Application End-to-End Flow: 'deeper-dive/robot-to-robot-comms.md'
    - Viam's Authentication: 'deeper-dive/security.md'
    - Control Package: 'deeper-dive/controls-package.md'    
  - Components:
    - Component FAQ: 'components/component-faq.md'  
    - Board: 'components/board.md'    
    - Base: 'components/base.md'
    - Motor: 'components/motor.md'
    - Servo: 'components/servo.md'
  - Services:
    - Vision: 'services/vision.md'
    - Data Capture: 'services/data-capture.md'    
  - Appendix:
    - Orientation Vector: 'appendix/orientation-vector.md'
    - Troubleshooting: 'appendix/troubleshooting.md'    
    - Viam Glossary: 'appendix/glossary.md'
  - SDKs:
    - Python SDK: 'https://python.viam.dev/'
theme:
  name: readthedocs
extra_css:
  - css/overrides.css
extra_javascript:
  - javascript/simple_auth.js
copyright: Copyright &copy; 2020 - 2022 Viam Robotics
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viamrobotics/tutorials-and-docs/
      name: docs source on github
markdown_extensions:
    - footnotes
    - admonition
    - codehilite

        
  

