name: Lint Markdown files
  
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.md'
      - .github/workflows/markdown-lint.yml
      - .markdownlint.yaml
  push:
    paths:
      - '**.md'
      - .github/workflows/markdown.yml
      - .markdownlint.yaml
  workflow_dispatch:

jobs:
  markdown_lint:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.yaml
          search_paths: |
            docs/
          exclude: |
            assets/
            themes/
            static/
            layouts/
